---
- name: useradd "{{ team_admin }}"
  ansible.builtin.user:
    name: "{{ team_admin }}"
    uid: "{{ team_admin_id }}"
    shell: /bin/bash
    create_home: true
    ssh_key_type: rsa
    ssh_key_bits: 4096
    password: "{{ h_password }}"
    state: present
