---
- include_vars: "../vars/sshd_vars.yml"

- name: configure sshd
  ansible.builtin.import_tasks:
    file: configure.yml

- name: add allowed
  vars:
    orcman: "{{ item }}"
  ansible.builtin.include_tasks:
    file: match_user.yml
  loop:
    - dave2001
    - root

- name: if ubuntu symlink /etc/init.d/sshd to /etc/init.d/ssh
  ansible.builtin.file:
    src: /etc/init.d/ssh
    dest: /etc/init.d/sshd
    owner: root
    group: root
    state: link
  when: needs_ssh_link is defined

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  when: ansible_distribution != "Ubuntu" and ansible_distribution_major_version | int < 18

- name: restart sshd (Ubuntu less than 18 LTS)
  ansible.builtin.service:
    name: ssh
    state: restarted
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int < 18