---
- include_vars: "../vars/sshd_vars.yml"

- name: configure sshd
  ansible.builtin.import_tasks:
    file: configure.yml

- name: add allowed
  vars:
    orcman: "{{ item }}"
  ansible.builtin.include_tasks:
    file: match_user.yml
  loop:
    - dave2001
    - root

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted