---
- name: change default chain policy (used to clean rules)
  ansible.builtin.iptables:
    chain: INPUT
    policy: ACCEPT

- name: clean rules on all chains of filter table
  ansible.builtin.iptables:
    table: filter
    flush: yes

- name: delete all user-defined chains on filter table
  shell: iptables -t filter -X

- name: Allow to loopback interface
  ansible.builtin.iptables:
    in_interface: lo
    chain: INPUT
    jump: ACCEPT
    comment: loopback

- name: Allow established and related state
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow ssh connection
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '22'
    jump: ACCEPT
    comment: ssh

- name: Allow splunk connection
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '8000'
    jump: ACCEPT
    comment: splunk
  when: inc_splunk_ports is defined

- name: Allow bind and ntp connection
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
    comment: bind and ntp
  when: inc_dns_ports is defined and inc_ntp_ports is defined
  with_items: [ '53', '127' ]

- name: disallow specific ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    source_port: "{{ item }}"
    jump: DROP
    comment: ftp
  with_items: [ '20', '21', '23' ]

- name: set default chain policy
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP

# ------- nat rules -------
- name: clean rules on all chains of nat table
  ansible.builtin.iptables:
    table: nat
    flush: yes

- name: delete all user-defined chains on nat table
  shell: iptables -t nat -X

# save
- name: save iptables config to disk
  shell: service iptables save
