---
- name: check for var file
  ansible.builtin.stat:
    path: "/depot/vault/{{ orcman }}.yml"
  register: varfile_state

- include_vars: "/depot/vault/{{ orcman }}.yml"
  when: varfile_state.stat.exists

- name: groupadd
  ansible.builtin.import_tasks:
    file: groupadd.yml
  when: orcman != "root"

- name: useradd
  ansible.builtin.import_tasks:
    file: useradd.yml

- name: add authorized key
  ansible.builtin.import_tasks:
    file: store_key.yml
  when: orcman == "hal9000"

- name: add authorized key
  ansible.builtin.import_tasks:
    file: add_key.yml
