---
- name: populate /etc/banner
  ansible.builtin.blockinfile:
    path: /etc/banner
    create: true
    owner: root
    group: root
    mode: '0644'
    state: present
    marker: "{mark} Security notice"
    block: |
      UNAUTHORIZED ACCESS TO THIS DEVICE IS PROHIBITED
      You must have explicit, authorized permission to access or configure this device.
      Unauthorized attempts and actions to access or use this system will result in
      civil and/or criminal penalties.
      All activies on this device are logged and monitored.
