---
<<<<<<< HEAD
- include_tasks: cleanup.yml
- include_tasks: copy.yml
- include_tasks: link.yml
=======
- name: banner - setup new /etc/banner
  ansible.builtin.file:
    path: "/etc/{{ item }}"
    state: absent
  loop:
    - banner
    - issue
    - issue.net
    - motd

- name: copy the new file in place
  ansible.builtin.copy:
    src: ../files/banner
    dest: /etc/banner
    owner: root
    group: root
    mode: '0644'

- name: Create new links
  ansbile.builtin.file:
    src: /etc/banner
    dest: "/etc/{{ item }}"
    state: link
  loop:
    - issue
    - issue.net
    - motd


>>>>>>> 9eb5ceb65ef5046e096604ae95712a1427f164dc
