#!/bin/bash

# Función para instalar bat desde el repositorio EPEL
install_bat_from_epel() {
    echo "Intentando instalar bat desde el repositorio EPEL..."
    sudo yum install -y epel-release
    sudo yum install -y bat
}

# Función para descargar e instalar bat directamente desde GitHub
install_bat_from_github() {
    echo "Descargando bat desde GitHub..."
    BAT_VERSION="0.18.1" # Reemplaza con la versión deseada
    BAT_BIN="https://github.com/sharkdp/bat/releases/download/v${BAT_VERSION}/bat-v${BAT_VERSION}-x86_64-unknown-linux-gnu.tar.gz"

    curl -Lo bat.tar.gz $BAT_BIN
    tar -xzf bat.tar.gz
    cd "bat-v${BAT_VERSION}-x86_64-unknown-linux-gnu"
    sudo cp bat /usr/local/bin/
}

# Intenta instalar bat desde EPEL
install_bat_from_epel

# Verifica si bat se instaló correctamente
if ! command -v batcat &> /dev/null
then
    echo "bat no se encontró en EPEL, intentando la instalación desde GitHub..."
    install_bat_from_github
fi

# Verifica la instalación final de bat
if command -v batcat &> /dev/null
then
    echo "bat instalado exitosamente."
else
    echo "Error: No se pudo instalar bat."
fi

