#!/bin/zsh

# Pregunta al usuario qué quiere hacer
echo "¿Qué quieres hacer?"
echo "1.- Buscar una palabra: grep -r \"palabra\" ruta"
echo "2.- awk"
read opcion

# Evalúa la opción seleccionada
case $opcion in
    1)
        # Si selecciona 1, muestra el mensaje
        echo "ejecuta: grep -r \"palabra\" /ruta"
        ;;
    2)
        # Si selecciona 2, muestra el mensaje
        echo "Ejecutar comando awk..."
        ;;
    *)
        # Si selecciona una opción inválida
        echo "Opción no válida."
        ;;
esac