#!/bin/bash

echo ""
# Check crontabs for the current user
echo "Crontab of the current user ($USER):"
crontab -l
echo ""
echo ""

# Check root's crontabs
echo "Root's Crontab:"
sudo crontab -l
echo ""
echo ""

# Check crontabs for all system users
echo "Crontabs of all system users:"
for username in $(cut -d: -f1 /etc/passwd); do
    echo "User: $username"
    sudo crontab -u $username -l
    echo ""
done

# Ask if the user wants to delete all crontabs
read -p "Do you want to delete crontabs for all users? (y/[enter]) " answer
case $answer in
    [Yy]* )
        for username in $(cut -d: -f1 /etc/passwd); do
            echo "Deleting crontab for user: $username"
            sudo crontab -u $username -r
        done
        echo "All crontabs have been deleted."
        ;;
    * )
        echo "Crontabs not deleted."
        ;;
esac

