#!/bin/bash

echo ""
# Check crontabs for the current user
echo "Crontab of the current user ($USER):"
crontab -l
echo ""
echo ""

# Check root's crontabs
echo "Root's Crontab:"
sudo crontab -l
echo ""
echo ""

# Check crontabs for all system users
echo "Crontabs of all system users:"
for username in $(cut -d: -f1 /etc/passwd); do
    echo "User: $username"
    sudo crontab -u $username -l
    echo ""
done
