#!/bin/zsh

echo "Ingrese la dirección IP:"
read ip_address

echo "Ingrese los puertos separados por comas (por ejemplo, 80,443,22):  o tambien copia los puertos generados de expo2"
read ports

command="nmap -sCV -p $ports $ip_address -oN targeted"

echo "Ejecutando el comando:"
echo "$command"

eval "$command"
