#!/bin/zsh

# Extract nmap information
function extractPorts(){
    local ports
    local ip_address

    ports="$(grep -oP '\d{1,5}/open' "$1" | awk '{print $1}' FS='/' | xargs | tr ' ' ',')"
    ip_address="$(grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' "$1" | sort -u | head -n 1)"

    echo -e "\n[*] Extracting information...\n" > extractPorts.tmp
    echo -e "\t[*] IP Address: $ip_address"  >> extractPorts.tmp
    echo -e "\t[*] Open ports: $ports\n"  >> extractPorts.tmp

    echo $ports | tr -d '\n' | xclip -sel clip
    echo -e "[*] Ports copied to clipboard\n"  >> extractPorts.tmp

    cat extractPorts.tmp
    rm extractPorts.tmp
}

# Ruta al archivo
file_path=$(pwd)/allPorts

# Verificar si el archivo existe
if [ -f "$file_path" ]; then
    echo "Procesando archivo $file_path..."
    extractPorts "$file_path"
else
    echo "El archivo $file_path no existe."
fi

