#!/bin/zsh

# Pedir al usuario que ingrese la dirección IP a bloquear
echo "Ingresa la dirección IP que deseas bloquear: \c"
read ip_address

# Ejecutar el comando de fail2ban-client para bloquear la dirección IP especificada en el jail de SSH
sudo fail2ban-client set sshd banip $ip_address

