#!/bin/zsh

echo ""
echo "# Comandos de fail2ban f2b

f2b = banea una IP
f2u = remueve la IP de jail
f2j = muestra jail

f2mod = modifica archivo de configuracion y reiniciar despues
f2r = reinicia f2ban
f2s = status 
rs2 = creado para security onion"

echo ""