#!/bin/bash

sudo apt-get install -y software-properties-common
wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
sleep 1
sudo apt-get update
sudo apt-get install grafana -y

sudo apt-get install prometheus prometheus-node-exporter grafana -y

#agregar los permisos
sudo chown -R grafana:grafana /var/lib/grafana
sudo chmod -R 750 /var/lib/grafana

#reiniciar las contrasenas
sudo grafana-cli admin reset-admin-password admin

sudo systemctl start grafana-server
#sudo systemctl restart grafana-server
sudo systemctl status grafana-server.service

#sudo systemctl enable grafana-server
#para ver los logs
#sudo journalctl -u grafana-server.service



