#!/bin/zsh

# Preguntar si se desea modificar /etc/sysctl.conf para Network Hardening
read -p "¿Desea ejecutar Network Hardening a /etc/sysctl.conf? (s/no-enter-): " response

# Verificar la respuesta
if [[ $response == "s" ]]; then
    # Hacer una copia de seguridad de /etc/sysctl.conf
    sudo cp /etc/sysctl.conf /etc/sysctl.conf.backup

    # Ajustes en /etc/sysctl.conf
    echo "
net.ipv4.conf.all.accept_source_route=0
ipv4.conf.all.forwarding=0
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.all.secure_redirects=0
net.ipv4.conf.all.send_redirects=0
net.ipv4.conf.all.rp_filter=2
net.ipv4.icmp_echo_ignore_all = 0
" | sudo tee -a /etc/sysctl.conf

    # Preguntar si se desea reiniciar el servicio
    read -p "¿Desea reiniciar el servicio ahora? (s/n): " restart_response

    # Verificar la respuesta sobre reinicio
    if [[ $restart_response == "s" ]]; then
        sudo sysctl --system  
    else
        echo "Operación cancelada. Los cambios requerirán un reinicio para surtir efecto."
    fi

else
    echo "Operación cancelada. No se realizaron cambios en /etc/sysctl.conf."
fi
