#!/bin/bash

# Agrega el repositorio de Sublime Text
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo gpg --dearmor -o /usr/share/keyrings/sublimehq-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/sublimehq-archive-keyring.gpg] https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list > /dev/null

# Actualiza la lista de paquetes
sudo apt update

# Instala Sublime Text
sudo apt install sublime-text

# Limpia los archivos generados durante la instalación
sudo rm /usr/share/keyrings/sublimehq-archive-keyring.gpg
sudo rm /etc/apt/sources.list.d/sublime-text.list

echo "Sublime Text ha sido instalado exitosamente."

exit 0


#// Settings in here override those in "Default/Preferences.sublime-settings",
$// and are overridden in turn by syntax-specific settings.
#{
#	
#	"font_size": 17,
#	"ignored_packages":
#	[
#		"Vintage",
#	],
#	"index_files": true,
#}
