#!/bin/zsh

echo "¿Qué estás buscando en Launchpad en Google?"
read search_query

search_query_url=$(echo "$search_query" | sed 's/ /%20/g')
search_url="https://www.google.com/search?q=launchpad%20$search_query_url"

firefox "$search_url"
