#!/bin/zsh


interfaces=$(ip addr | awk '/^[0-9]+:/ {gsub(/:/,"",$2); iface=$2} /^    inet / {print iface, $2}')

echo ""

# Mostrar las interfaces y sus direcciones IP
echo "                           Interfaces de red y sus direcciones IP:"
echo ""
echo "$interfaces"
echo ""



# Preguntar qué interfaz quieres configurar
read "interfaz?Ingresa el nombre de la interfaz que quieres configurar: "

# Preguntar por la nueva MAC
read "nueva_MAC?Ingresa la nueva MAC: "

# Mostrar el estado actual de la interfaz
echo "Estado actual de la interfaz $interfaz:"
ip link show $interfaz | grep "link/ether"

# Cambiar la dirección MAC
sudo ip link set dev $interfaz address $nueva_MAC

# Reiniciar la interfaz
sudo ip link set dev $interfaz down
sudo ip link set dev $interfaz up

# Mostrar el estado actual de la interfaz después del cambio
echo "Estado actual de la interfaz $interfaz:"
ip link show $interfaz | grep "link/ether"
