#!/bin/bash

#

curl --request GET \
  --url 'https://www.tenable.com/downloads/api/v2/pages/nessus/files/Nessus-10.6.4-ubuntu1404_amd64.deb' \
  --output 'Nessus-10.6.4-ubuntu1404_amd64.deb'




# Instala Nessus
sudo dpkg -i Nessus-10.6.4-ubuntu1404_amd64.deb



# Verifica el hash en la página oficial
echo 'Verifica el hash en la página oficial que coincida: https://www.tenable.com/downloads/nessus?loginAttempted=true'

# Calcula y muestra el hash SHA-256 del archivo Nessus
sha256sum Nessus-10.6.1-debian10_amd64.deb

echo ''

echo 'also for dockers: docker pull tenable/nessus:latest-ubuntu'



# Instrucciones para iniciar Nessus
echo 'para iniciar nessus solo escribe nessus o systemctl start nessusd.service'

rm -f Nessus-10.6.4-ubuntu1404_amd64.deb
echo ''
echo ''

echo "ve a la pagina oficial para descargarlo, cambia de versiones"
echo "https://www.tenable.com/downloads/nessus?loginAttempted=true"
