#!/bin/zsh

# Obtener la ruta completa del archivo "ips.txt" en el directorio actual
ips_file="$(pwd)/ips.txt"

# Verificar que el archivo exista
if [ ! -f "$ips_file" ]; then
  echo "El archivo 'ips.txt' no existe en el directorio actual."
  exit 1
fi

# Leer el archivo línea por línea y ejecutar el script para cada dirección IP
while IFS= read -r ip_address; do
  # Ejecutar ping en la dirección IP
  ping_output=$(ping -c 1 "$ip_address")

  # Extraer la dirección IP del resultado de ping
  ip_address=$(echo "$ping_output" | awk -F'[()]' '/PING/{print $2}')

  # Ejecutar nslookup para obtener el nombre de la máquina
  host_name=$(nslookup "$ip_address" | awk '/name =/{print substr($0,index($0,$NF))}')

  # Determinar el sistema operativo basado en la respuesta de ping
  os="Desconocido"
  if echo "$ping_output" | grep -q "ttl=[1-9][0-9]"; then
    os="Linux/Unix"
  elif echo "$ping_output" | grep -q "ttl=[1-9]"; then
    os="Windows"
  fi

  # Imprimir los resultados con espacios adicionales
  if [ -n "$ip_address" ]; then
    echo ""
    echo "Dirección IP: $ip_address"
  fi

  if [ -n "$host_name" ]; then
    echo "Nombre de la máquina: $host_name"
  fi

  echo "Sistema operativo: $os"
  echo ""

done < "$ips_file"
