#!/bin/bash
echo ""
echo "ejecutando nmap -sn /24"
echo ""
echo ""

# Verifica que se haya proporcionado una dirección IP como argumento
if [ $# -ne 1 ]; then
    echo "Por favor, proporciona una dirección IP como argumento."
    exit 1
fi

# Obtiene la dirección IP del argumento
subnet="$1"

# Crea un archivo temporal
tempfile=$(mktemp)

# Ejecuta el comando nmap y filtra la salida
nmap -sn $subnet.0/24 | grep -oP '\d{1,3}(\.\d{1,3}){3}' | while read -r line; do
    echo "$line is up" | tee -a $tempfile
done
echo ""
echo ""
echo ""
echo "hecho"
echo ""

# Pregunta si desea guardar el archivo
read -p "¿Desea guardar un archivo de IPs? (s/n): " guardar
echo ""
echo ""





if [[ $guardar == "s" ]]; then
    # Copia el archivo temporal a la ruta actual como ips.txt
    cp $tempfile ./ips1.txt
    sed 's/ is up//' ips1.txt > ips.txt

    echo "Archivo guardado como ips.txt"
fi

# Elimina el archivo temporal
rm $tempfile
echo ""
echo "*** Precausion*** Solo esta echo para /24"
echo ""