#!/bin/bash

# Función para mostrar el mensaje de ayuda y preguntar si desea continuar
show_help_and_confirm() {
    echo
    echo "El comando que este script ejecuta es:"
    echo "ps -eo user,comm,pid "
    echo
    echo "Presione Enter para continuar o 'c' para salir."

    # Preguntar al usuario si desea continuar
    read -p "Deseas continuar [c/S] " response

    # Convertir la respuesta a minúsculas
    response=$(echo "$response" | tr '[:upper:]' '[:lower:]')

    # Si la respuesta es 'c', salir del script
    if [ "$response" == "c" ]; then
        echo "Saliendo del script."
        exit 0
    fi
}

# Verificar si se pasó el argumento -h
if [ "$1" == "-h" ]; then
    show_help_and_confirm
fi

mostrar_procesos() {
    ps_output=$(ps -eo user,comm)
    lines=("${(@f)ps_output}")

    for line in "${lines[@]:2}"; do
        user=$(echo $line | awk '{print $1}')
        process=$(echo $line | awk '{print $2}')
        printf "%-15s %-20s\n" "$user" "$process"
    done
}

mostrar_procesos | sort | uniq

echo ""
echo "procesos | grep -v root" | xclip -selection clipboard
echo ""
echo "Fin del script."
echo ""
echo "Ejecuta este comando para que no muestre los procesos de root:"
echo "procesos | grep -v root | sort | uniq "
echo ""
echo "También ese comando ya fue copiado al portapapeles."
echo ""
echo "Puedes usar:\nprocesos > procesos\n"
echo "Esto para crear un archivo y buscar algún proceso en específico."
echo ""
echo "Ejemplos:\ncat procesos | sort | uniq | grep -v palabra1\n"
#awk '{print $1 "	" $2}' procesos | uniq | sort | grep -v root
echo "grep -i para incluir, grep -v para excluir root por ejemplo\n"
echo ""

# Nuevas funcionalidades agregadas aquí
echo "¿Deseas crear un archivo llamado 'procesos'? (s/N):"
read crearArchivo

if [[ $crearArchivo == 's' ]]; then
    mostrar_procesos > procesos
    echo "Archivo 'procesos' creado."
    echo "¿Deseas buscar algo en el archivo 'procesos'? (s/N):"
    read buscarEnArchivo

    if [[ $buscarEnArchivo == 's' ]]; then
        echo "Introduce la palabra a buscar:"
        read palabra
        cat procesos | sort | uniq | grep -i "$palabra"
    fi
fi
