#!/bin/bash

# Función para mostrar el mensaje de ayuda y preguntar si desea continuar
show_help_and_confirm() {
    echo
    echo "El comando que este script ejecuta es:"
    echo "ps -eo "
    echo
    echo "Presione Enter para continuar o 'c' para salir."

    # Preguntar al usuario si desea continuar
    read -p "Deseas continuar [c/S] " response

    # Convertir la respuesta a minúsculas
    response=$(echo "$response" | tr '[:upper:]' '[:lower:]')

    # Si la respuesta es 'c', salir del script
    if [ "$response" == "c" ]; then
        echo "Saliendo del script."
        exit 0
    fi
}

# Verificar si se pasó el argumento -h
if [ "$1" == "-h" ]; then
    show_help_and_confirm
fi

mostrar_procesos() {
    echo "Usuarios, Procesos y PIDs:"
    echo "----------------------------"

    # Obtener la lista de usuarios, procesos y PIDs
    ps_output=$(ps -eo user,comm,pid)
    lines=("${(@f)ps_output}")

    # Imprimir el encabezado
    printf "%-15s %-20s %-10s\n" "Usuario" "Proceso" "PID"
    echo "----------------------------"

    # Imprimir la lista de usuarios, procesos y PIDs en un formato más legible
    for line in "${lines[@]:2}"; do
        user=$(echo $line | awk '{print $1}')
        process=$(echo $line | awk '{print $2}')
        pid=$(echo $line | awk '{print $3}')
        printf "%-15s %-20s %-10s\n" "$user" "$process" "$pid"
    done

}

mostrar_procesos | sort



echo ""

echo " procesos | grep -v root" | sort | xclip -selection clipboard 

echo ""

  echo "Fin del script."
    echo ""
    echo "Ejecuta este comando para que no muestre los procesos de root:"
    echo "procesos | grep -v root | sort "
    echo ""
    echo "Tambien ese comando ya fue copiado al portapapeles"
    echo ""
    echo "Puedes usar:\nprocesos > procesos\n"
    echo "Esto para crear un archivo y buscar algun proceso en especifico"
    echo ""
    echo "ejemplos:\ncat procesos | sort | uniq | grep -v palabra1"
    echo "awk '{print \$1 \"\\t\" \$2}' procesos | uniq | sort | grep -v root\n"
    #echo "awk '{print $1 "\t" $2}' procesos | uniq | sort | grep -v root\n"
    echo "grep -i para incluir, grep -v para excluir root por ejemplo"


# Nuevas funcionalidades agregadas aquí
echo "¿Deseas crear un archivo llamado 'procesos'? (s/N):"
read crearArchivo

if [[ $crearArchivo == 's' ]]; then
    mostrar_procesos > procesos
    echo "Archivo 'procesos' creado."
    echo "¿Deseas buscar algo en el archivo 'procesos'? (s/N):"
    read buscarEnArchivo

    if [[ $buscarEnArchivo == 's' ]]; then
        echo "Introduce la palabra a buscar:"
        read palabra
        cat procesos | sort | uniq | grep -i "$palabra"
    fi
fi
