#!/bin/zsh

# Obtener la lista de archivos en la carpeta "$HOME/Downloads/vpnitos"
file_list=($HOME/Downloads/.vpnitos/*)

# Crear un menú de configuración con dialog
menu_options=()
for ((i=0; i<${#file_list[@]}; i++)); do
    file="${file_list[$i]}"
    file_name=$(basename "$file")  # Obtener solo el nombre del archivo
    menu_options+=("$i" "$file_name")
done
menu_options+=("0" "Salir")

option=$(/usr/bin/dialog --backtitle "Menú de configuración" --title "Configuración" \
--menu "Selecciona un archivo:" 25 50 4 "${menu_options[@]}" 2>&1 >/dev/tty)

# Verificar la opción seleccionada
if [[ $option == "0" ]]; then
    echo "Saliendo..."
elif [[ $option =~ ^[0-9]+$ && $option -lt ${#file_list[@]} ]]; then
    # Obtener el nombre del archivo seleccionado
    selected_file="${file_list[$option]}"
    selected_file_name=$(basename "$selected_file")  # Obtener solo el nombre del archivo seleccionado

    # Ejecutar el comando sudo openvpn con el archivo seleccionado
    echo "Conectando con OpenVPN usando el archivo: $selected_file_name"
    sudo openvpn "$selected_file"
else
    echo "Opción inválida."
fi
