#!/bin/zsh

# Guardar una copia de seguridad del archivo sources.list original
sudo cp /etc/apt/sources.list /etc/apt/sources.list.backup

# Eliminar todos los archivos en /etc/apt/sources.list.d/ para borrar repositorios adicionales
sudo rm -rf /etc/apt/sources.list.d/*

# Restaurar el contenido predeterminado del archivo sources.list
echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" | sudo tee /etc/apt/sources.list

# Actualizar la lista de paquetes
sudo apt update

#wget -q -O - https://archive.kali.org/archive-key.asc  | apt-key add

echo "ejecutar: wget -q -O - https://archive.kali.org/archive-key.asc  | apt-key add"