#!/bin/bash

# Lista de paquetes a instalar
paquetes=("rkhunter" "chkrootkit" )


# Función para verificar si un paquete está instalado (Debian/Ubuntu/Kali)
paquete_instalado_apt() {  
    dpkg -l "$1" | grep -q '^ii'  
}

# Función para verificar si un paquete está instalado (CentOS/RHEL)
paquete_instalado_yum() {
    yum list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Fedora)
paquete_instalado_dnf() {
    dnf list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Arch Linux)
paquete_instalado_pacman() {
    pacman -Qi "$1" &> /dev/null
}

# Detectar el sistema operativo
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
fi

# Instalar paquetes basados en el sistema operativo
for paquete in "${paquetes[@]}"; do
    case $OS in
        "debian"|"ubuntu"|"kali")
            if ! paquete_instalado_apt "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo apt-get install -y "$paquete"
            fi
            ;;
        "centos"|"rhel")
            if ! paquete_instalado_yum "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo yum install -y "$paquete"
            fi
            ;;
        "fedora")
            if ! paquete_instalado_dnf "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo dnf install -y "$paquete"
            fi
            ;;
        "arch")
            if ! paquete_instalado_pacman "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo pacman -S --noconfirm "$paquete"
            fi
            ;;
        *)
            ;;
    esac
done












echo "modificar los archivos"
echo "sudo nano /etc/rkhunter.conf"
echo "sudo nano /etc/default/rkhunter"
read -p "Quieres modificar los archivos? s/enter: " modificar



if [[ $modificar == "s" ]]; then
    sudo rkhunconf
    sudo rkhuncron
    echo "Archivos modificados con scripts"
    sleep 1
fi

# Pregunta al usuario si quiere actualizar la base de datos
read -p "Quieres actualizar la base de datos? s/enter: " actualizar

if [[ $actualizar == "s" ]]; then
    sudo rkhunter --update
fi


sleep 1
#listado de binarios abajo se ejecuta
#sudo rkhunter --propupd

# Preguntar al usuario si quiere ejecutar el escaneo
echo "¿Quieres ejecutar el escaneo ahora? (s/n): "
read respuesta

if [[ $respuesta = "s" ]]; then
    # Si el usuario responde 's', ejecutar rkhunter
    echo "Ejecutando rkhunter..."
    sudo rkhunter --propupd
    sudo rkhunter --check -sk
else
    # Si el usuario presiona enter o cualquier otra tecla, mostrar cómo ejecutarlo más tarde
    echo "Para escanear ejecute: sudo rkhunter --check -sk"
fi


echo ""
echo "comandos utiles"
echo "sudo rkhunter --versioncheck"
echo ""
echo "Para correr el scaner de nuevo"
echo "sudo rkhunter --check -sk"
echo ""
echo "usa chkrootkit asi:"
echo ""
echo "chkrootkit"