#!/bin/bash

while true; do
    files=("/root/.bashrc" "/root/.shrc" "/root/.cshrc" "/root/.tcshrc" "/root/.zshrc")

    echo "Selecciona un archivo para inspeccionar:"
    for ((i=0; i<${#files[@]}; i++)); do
        echo " $((i+1)). ${files[i]}"
    done

    read -p "O introduce 'q' para salir: " selection

    if [ "$selection" == "q" ]; then
        echo "Saliendo del script."
        break
    elif [ "$selection" -ge 1 ] && [ "$selection" -le ${#files[@]} ]; then
        sudo cat "${files[selection-1]}"
    else
        echo "Selección no válida. Inténtalo de nuevo."
    fi
done
