#!/bin/bash

#alias para iniciar
echo "alias splunk='sudo /opt/splunk/bin/splunk start'"  >> ~/.zshrc

# Navegar al directorio /opt
cd /opt

# Descargar Splunk
sudo wget -O splunk-9.1.2-b6b9c8185839-Linux-x86_64.tgz "https://download.splunk.com/products/splunk/releases/9.1.2/linux/splunk-9.1.2-b6b9c8185839-Linux-x86_64.tgz"

# Descomprimir el archivo tar
sudo tar xvzf splunk-9.1.2-b6b9c8185839-Linux-x86_64.tgz

# Navegar al directorio de Splunk
cd splunk/bin/

# Iniciar Splunk
sudo ./splunk start



# Recargar el archivo .bashrc para aplicar los cambios
source ~/.zshrc
