#!/bin/bash

# Crear un archivo temporal
tempfile=$(mktemp)

# Ejecutar el comando y almacenar la salida en el archivo temporal
ssa1 > "$tempfile"

# Puedes realizar otras operaciones con el archivo si es necesario
# Por ejemplo, mostrar su contenido con cat
cat "$tempfile"


# Verifica el estado del servicio SSH
if systemctl is-active ssh &> /dev/null; then
  echo "El servicio SSH está          **^^   ACTIVO   ^^**."
  echo ""
  read "desactivar_ssh?¿Desea  * DESACTIVAR * el servicio SSH? (s para si/Enter para continuar)"
  if [[ "$desactivar_ssh" == "s" ]]; then
    sudo systemctl stop ssh
    echo ""
    echo "El servicio SSH ha sido         ***  DESACTIVADO  *** ."
  else
    echo "No se ha desactivado el servicio SSH."
  fi
else
  echo "El servicio SSH está              ***  INACTIVO  ***."
  echo ""
  read "activar_ssh?¿Desea  * ACTIVAR * el servicio SSH? (s para si/Enter para continuar)"
  if [[ "$activar_ssh" == "s" ]]; then
    sudo systemctl start ssh
    echo
    interfaces=$(ip addr | awk '/^[0-9]+:/ {gsub(/:/,"",$2); iface=$2} /^    inet / {print iface, $2}')
  echo ""
    echo "El servicio SSH ha sido         **^^  ACTIVADO  ^^**."

    echo -e "\n\n\n\nTu IP es: $(/usr/sbin/ifconfig eth0 | grep "inet " | awk '{print $2}')"
    echo "*** Tu usuario es: *** "
    whoami
  else
    echo "No se ha activado el servicio SSH."
  fi
fi

