#!/bin/zsh

# Ejecutar el comando y almacenar la salida en una variable
output=$(systemctl status ssh)

echo ""
echo "SSH status:"
# Buscar la línea que contiene 'Active:' en la salida y mostrarla
echo "$output" | grep 'Active:'

# Agregar un renglón de separación
echo ""

#ip addr | grep "inet "  #con inet
#ip -4 addr show | awk '/inet/ && /brd/ {print $NF, $2}'    #con subned /24
ip -4 addr show | awk '/inet/ && !/127.0.0.1/ {split($2, a, "/"); print $NF, a[1]}'


# Agregamos el mensaje con la IP local
echo -e "\n\n\n\nTu IP es: $(/usr/sbin/ifconfig wlan0 | grep "inet " | awk '{print $2}')"
echo ""
echo "  *** user ***"
whoami
echo ""
echo ""
echo " *** Puerto de escucha: ***"
grep -E '^#?Port ' /etc/ssh/sshd_config
