#!/bin/bash

echo ""

# Ask if the user wants to perform SSH hardening in sshd_config
read -p "Do you want to perform SSH hardening in sshd_config? (y/n): " response

# Verify the response
if [[ $response == "y" ]]; then

    # Backup the sshd_config file
    sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup

    # Define the lines to search for and insert into the file
    lines_to_insert=(
        "PermitRootLogin no"
        "PermitEmptyPasswords no"
        "KerberosAuthentication no"
        "GSSAPIAuthentication no"
        "X11Forwarding no"
        "MaxAuthTries 3"
        "LoginGraceTime 20"
        "PermitUserEnvironment no"
        "AllowAgentForwarding no"
        "AllowTcpForwarding no"
        "PermitTunnel no"
        "MaxSessions 2"
        "Compression no"
        "TCPKeepAlive no"
        "UseDNS no"
        "LogLevel VERBOSE"
        "PubkeyAuthentication yes"
        "Banner /etc/mctcbanner"
    )

    # Replace or add the specified lines in the sshd_config file
    for line in "${lines_to_insert[@]}"; do
        if ! sudo grep -q "^$line" /etc/ssh/sshd_config; then
            echo "$line" | sudo tee -a /etc/ssh/sshd_config
        else
            sudo sed -i "s/^$line.*/$line/" /etc/ssh/sshd_config
        fi
    done

    

    #echo "Current sshd configuration:"
    #sudo sshd -T
    echo ""
        echo ""
            echo ""

    echo ""
    echo "Check changes in:"
    echo "cat /etc/ssh/sshd_config"
    echo ""
    echo "Backup in:"
    echo "cat /etc/ssh/sshd_config.backup"
    echo ""
    echo ""
    echo ""
    echo " RESTART THE SSH SERVICE TO APPLY CHANGES"
fi

    echo ""
    echo ""
    echo ""
    echo "**************** END ****************"
    echo ""
        echo ""



# Ask if the user wants to check the current SSH configuration
read -p "Press Enter to verify the current SSH configuration or 'c' to cancel: " check_config

# Check if the user pressed Enter or entered 'c'
if [[ $check_config == "" ]]; then
    echo "Current sshd configuration:"
    sudo sshd -T
elif [[ $check_config == "c" ]]; then
    echo "Operation cancelled."
else
    echo "Invalid input. Operation cancelled."
fi

echo ""
echo "**************** END ****************"

echo ""

echo "note: if you get error: /run/sshd missing check notes script"


#in case missing /run/sshd apply:
#sudo mkdir /run/sshd
#sudo chmod 755 /run/sshd
#sudo systemctl restart ssh
#sudo sshd -T