#!/bin/zsh

if [ "$1" = "-f" ]; then
    output_file="temp-$(date +"%Y%m%d%H%M%S")"  # Nombre del archivo con la marca de tiempo actual
    command_output=$(paste <(cat /sys/class/thermal/thermal_zone*/type) <(cat /sys/class/thermal/thermal_zone*/temp) | column -s $'\t' -t | sed 's/\(.\)..$/.\1°C/')
    echo "$command_output" > "$output_file"
else
    paste <(cat /sys/class/thermal/thermal_zone*/type) <(cat /sys/class/thermal/thermal_zone*/temp) | column -s $'\t' -t | sed 's/\(.\)..$/.\1°C/'
fi
