#!/bin/bash



cd
git clone https://github.com/gpakosz/.tmux.git
ln -s -f .tmux/.tmux.conf
cp .tmux/.tmux.conf.local .



conf_file="$HOME/.tmux.conf"

# Agrega el contenido al archivo sin borrar nada
cat << EOF >> "$conf_file"
# Send prefix
set-option -g prefix C-b
unbind-key C-b
bind-key C-b send-prefix

# Use Alt-arrow keys to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left previous-window
bind -n S-Right next-window

# Mouse mode
#setw -g mouse on

# Set easier window split keys
bind-key v split-window -h
bind-key h split-window -v

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."
EOF

echo "Las líneas se han agregado al final del archivo $conf_file."
