---
- name: make sure "{{ quarantine_path }}/crons" exists
  ansible.builtin.file:
    path: "{{ quarantine_path }}"
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: remove any crons found
  ansible.builtin.shell: |
    for c in $(/bin/ls /var/spool/cron)
    do
        /bin/mv /var/spool/cron/${c}  {{ quarantine_path }}/crons/
    done
