---
# Funny addresses were found in /etc/hosts in NetLab
# this is meant to make the default /etc/hosts cleaner
# the most notable example was a routable IP address
# assigne to `localhost`, this allows for a "cleaner" /etc/hosts
# by making sure localhost is to appropriate addresses and defines
# the main NIC IP address is associate with the host's name
- name: adjust existing /etc/hosts
  ansible.builtin.replace:
    path: /etc/hosts
    backup: true
    regexp: '^((?!#).+)$'  # match only if not commented out
    replace: '# \1'
- name: ensure only entries are loopback and main interface IP
  ansible.builtin.blockinfile:
    path: /etc/hosts
    regexp: 'BOF'
    marker: "# {mark} adjusted /etc/hosts"
    block: |
      127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4
      ::1 localhost localhost.localdomain localhost6 localhost6.localdomain6
      {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} {{ ansible_nodename }} 
