---
- name: adjust existing /etc/hosts
  ansible.builtin.replace:
    path: /etc/hosts
    backup: true
    regexp: '^((?!#).+)$'  # match only if not commented out
    replace: '# \1'
- name: ensure only entries are loopback and main interface IP
  ansible.builtin.blockinfile:
    path: /etc/hosts
    regexp: 'BOF'
    marker: "# {mark} adjusted /etc/hosts"
    block: |
      127.0.0.1 localhost localhost.localdomain
      ::1 localhost localhost.localdomain
      {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} {{ ansible_nodename }} 
