---
# - name: lock suspect users with uid under 1024
  # ansible.builtin.shell: |
  #   for u in $(awk -F: '($3 < 1024) {print $1}' /etc/passwd)
  #   do
  #       if [[ "${u}" != "root" ]]; then
  #           usermod -L ${u}
  #       fi
  #       if [[ "${u}" != "root" && $(awk -F: '{print $3}') == "0" ]]; then
  #         touch "{{ quarantine_path }}/non_uid0_user_${u}"
  #       fi
  #       case ${u} in
  #         root|sync|shutdown|halt|sysadmin) skip=y ;;
  #         syslog|landscape|messagebus) usermod -s /bin/false ${u} ;;
  #         *) usermod -s /usr/sbin/nologin ${u} ;;
  #       esac
  #   done
  # args: 
  #   executable: /bin/bash

- name: lock suspect users under uid 1024
  ansible.builtin.getent:
    database: passwd

- name: lock users under uid 1024 unless special
  ansbile.builtin.command: "/usr/sbin/usermod -L {{ item }}"
  when: gentent_passwd["{{ item }}"][1] | int < 1024 and (item != root or item != sync or item != shutdown  item != halt or item != syadmin)
  with_items: "{{ gentent_passwd.keys() }}"
