---

- hosts: all
  become: true
  tasks:

  - name: install ufw
    ansible.builtin.package:
      name: ufw
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]
  
  - name: start ufw
    ansible.builtin.service:
      name: ufw
      state: started
      enabled: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: allow ssh
  - community.general.ufw:
      rule: allow
      name: OpenSSH
    when: ansible_distribution in ["Debian", "Ubuntu"]

- name: allow all access to port 53 (dns)
  community.general.ufw:
    rule: allow
    port: '53'
  when: ansible_distribution == "Debian"

- name: allow all access to port 123 (ntp)
  community.general.ufw:
    rule: allow
    port: '123'
  when: ansible_distribution == "Debian"

- name: allow all access to port 80 (http)
  community.general.ufw:
    rule: allow
    port: '80'
  when: ansible_distribution == "Ubuntu"

- name: allow all access to port 443 
  community.general.ufw:
    rule: allow
    port: '443'
  when: ansible_distribution == "Ubuntu"

- name: Deny all access to ftp
  community.general.ufw:
    rule: deny
    name: ftp
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Deny all access to telnet
  community.general.ufw:
    rule: deny
    name: telnet
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Deny all access to port 25 (smtp)
  community.general.ufw:
    rule: deny
    port: '25'
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: restart ufw
  ansible.builtin.service:
    name: ufw
    state: restarted
  when: ansible_distribution in ["Debian", "Ubuntu"]




