---

- hosts: all
  become: true
  tasks:

  - name: Install epel-release for EL distros
    ansible.builtin.package:
      name: epel-release
      state: latest
    when: ansible_distribution in ["CentOS", "Fedora"]

  - name: Install rkhunter and lynis
    ansible.builtin.package:
      name:
        - rkhunter
        - lynis
      state: latest
  
  - name: start rkhunter  and lynis
    ansible.builtin.service:
      name: 
        - rkhunter
        - lynis
      state: started
      enabled: yes

  - name: rkhunter check Run
    ansible.builtin.command: rkhunter --check

  - name: lynis check Run
    ansible.builtin.command: lynis audit system  













# - name: Configure rkhunter.conf
#     ansible.builtin.template:
#       src: rkhunter.conf.j2        # NEED TO UPLOAD EDITED CONFIG FILE - SET UP NOTIFICATIONS HERE
#       dest: /etc/rkhunter.conf

#   - name: Configure /etc/default/rkhunter.conf to set up cronjob
#     ansible.builtin.template:
#       src: rkhunter.default.update       # HOW TO UPDATE TO NEW FILE WITHOUT DELETING ORIGINAL FILE?
#       dest: /etc/default/rkhunter.conf
  
#   - name: Create logfile directory
#     ansible.builtin.file:
#       path: '/var/log/rkhunter/'  # By default, on debian, the log file is /var/log/rkhunter.log
#       state: 'directory'
#       mode: 0644

#   - name: rkhunter update
#     ansible.builtin.command: rkhunter --update
#     register: rkhunter_update
#     failed_when: rkhunter_update.rc != 2 and rkhunter_update.rc != 0

#   - name: rkhunter propupd
#     ansible.builtin.command: rkhunter --propupd

# - name: Run CRON job to load data at every 30th minute of every hour.
#   cron:
#     name: "load_data"
#     user: "hal9000"
#     weekday: "*"
#     minute: "30"
#     hour: "*"
#     job: "python3 /path/to/my/script/loadScript.py > /home/ec2-user/loadData_result 2>&1"
#     state: present





