---

- hosts: dnsntp
  become: true
  tasks:

  - name: Install ntp
    ansible.builtin.package:
      name:
        - ntp
      state: latest
  
  - name: start ntp
    ansible.builtin.service:
      name: 
        - ntp
      state: started
      enabled: yes

  - name: Backup default ntp.conf file
    anisble.builtin.command: cp -p /etc/ntp.conf /etc/ntp_default.conf

  - name: update ntp.conf file
    ansible.builtin.template:
      src: ../files/ntp.conf.j2
      dest: /etc/ntp.conf

  - name: restart ntp
    ansible.builtin.service:
      name: 
        - ntp
      state: restarted