---
- name: open the pod bay doors Hal
  gather_facts: true
  hosts: all:!discovery
  become: true
  vars:
    ansible_user: "{{ initial_user }}"
    ansible_password: "{{ initial_password }}"
    ansible_become_user: root
    ansible_become_password: "{{ initial_password }}"
  tasks:
    - name: fix repos CentOS6 (if appropriate)
      ansible.builtin.include_role:
        name: fix_repos
      when: iscentos6 is defined or isdebian8 is defined

    - name: shields up
      vars:
        battle_station: "{{ item }}"
      ansible.builtin.include_role:
        name: shields_up
      loop:
        - file_archive
        - crons
        - dns
        - hosts

    # # CentOS6 requires a package to work properly
    # - name: install libselinux-python
    #   vars:
    #     ansible_user: "{{ initial_user }}"
    #   ansible.builtin.package:
    #     name: libselinux-python
    #     state: present
    #   when: iscentos6 is defined

    - name: user_setup
      vars:
        orcman: root
      ansible.builtin.include_role:
        name: user_setup

    - name: user_setup
      vars:
        orcman: dave2001
        add_key: true
      ansible.builtin.include_role:
        name: user_setup

    - name: do_sudo
      vars:
        orcman: dave2001
      ansible.builtin.include_role:
        name: do_sudo 