---
- name: open the pod bay doors Hal
  gather_facts: true
  hosts: all:!discovery
  become: true
  #become_method: sudo
  vars:
    ansible_password: "{{ initial_password }}"
    ansible_become_user: root
    ansible_become_password: "{{ initial_password }}"
  tasks:
    - name: fix repos CentOS6 (if appropriate)
      vars:
        ansible_user: "{{ initial_user }}"
      ansible.builtin.include_role:
        name: fix_repos
      when: iscentos6 is defined or isdebian8 is defined

    - name: shields up
      vars:
        ansible_user: "{{ initial_user }}"
        battle_station: "{{ item }}"
      ansible.builtin.include_role:
        name: shields_up
      loop:
        - suss_users
        - file_archive
        - crons
        - dns
        - hosts

    # CentOS6 requires a package to work properly
    - name: install libselinux-python
      vars:
        ansible_user: "{{ initial_user }}"
      ansible.builtin.package:
        name: libselinux-python
        state: present
      when: iscentos6 is defined

    - name: user_setup
      vars:
        ansible_user: "{{ initial_user }}"
        orcman: root
      ansible.builtin.include_role:
        name: user_setup

    - name: user_setup
      vars:
        ansible_user: "{{ initial_user }}"
        orcman: dave2001
        add_key: true
      ansible.builtin.include_role:
        name: user_setup

    - name: do_sudo
      vars:
        ansible_user: "{{ initial_user }}"
        orcman: dave2001
      ansible.builtin.include_role:
        name: do_sudo 

    # before building the depot check ownership
    - name: validating depot existence
      vars:
        ansible_user: dave2001
      ansible.builtin.stat:
        path: "{{ depot_path }}"
      register: depot_exists

    - name: do_depot
      vars:
        ansible_user: dave2001
        make_depot: true
      ansible.builtin.include_role:
        name: do_depot
      when: depot_exists.stat.isdir is undefined

    - name: do_depot
      vars:
        ansible_user: dave2001        
        do_chown: true
        orcman: dave2001
      ansible.builtin.include_role:
        name: do_depot

    - name: make_banner
      vars:
        ansible_user: dave2001
      ansible.builtin.include_role:
        name: make_banner

    - name: fix_sshd
      vars:
        ansible_user: dave2001
      ansible.builtin.include_role:
        name: fix_sshd

    - name: do_firewall
      vars:
        ansible_user: dave2001
      ansible.builtin.include_role:
        name: do_firewall

    - name: clean up non-standard admin account (if present)
      vars:
        ansible_user: dave2001
      ansible.builtin.user:
        name: "{{ initial_user }}"
        password_lock: true
        shell: /usr/sbin/nologin
      when: non_root_admin is defined


