---
- name: wake the crew
  gather_facts: true
  hosts: localhost
  connection: local
  tasks:
    - name: user_setup
      ansible.builtin.include_role:
        name: user_setup
      vars:
        orcman: "hal9000"
        add_key: true
        store_key: true
    - name: do_sudo
      ansible.builtin.include_role:
        name: do_sudo 
      vars:
        orcman: "hal9000"
    - name: user_setup
      ansible.builtin.include_role:
        name: user_setup
      vars:
        orcman: "dave2001"
        add_key: true
    - name: do_sudo
      ansible.builtin.include_role:
        name: do_sudo 
      vars:
        orcman: "dave2001"
    - name: depot_fix
      ansible.builtin.include_role:
        name: depot_fix


