---
- name: docking the pod
  gather_facts: true
  hosts: all:!discovery
  become: true
  become_method: sudo
  vars:
    ansible_user: dave2001
    ansible_become_user: root
  tasks:
     # before building the depot check ownership
    - name: validating depot existence
      ansible.builtin.stat:
        path: "{{ depot_path }}"
      register: depot_exists

    - name: do_depot
      make_depot: true
      ansible.builtin.include_role:
        name: do_depot
      when: depot_exists.stat.isdir is undefined

    - name: do_depot
      vars:
        do_chown: true
        orcman: dave2001
      ansible.builtin.include_role:
        name: do_depot

    - name: make_banner
      ansible.builtin.include_role:
        name: make_banner

    - name: fix_sshd
      ansible.builtin.include_role:
        name: fix_sshd

    - name: do_firewall
      ansible.builtin.include_role:
        name: do_firewall

    - name: shields up
      vars:
        battle_station: suss_users
      ansible.builtin.include_role:
        name: shields_up

    - name: do_sudo
      vars:
        orcman: dave2001
        sudo_pass2: true
      ansible.builtin.include_role:
        name: do_sudo 

    - name: clean up non-standard admin account (if present)
      ansible.builtin.user:
        name: sysadmin
        password_lock: true
        shell: /usr/sbin/nologin
      when: non_root_admin is defined


