---
- name: open the pod bay doors Hal
  gather_facts: true
  hosts: all
  tasks:
    - name: fix centos libselinux-python issue
      ansible.builtin.package:
        name: libselinux-python
        state: present
      when: ansible_facts['distribution'] == "CentOS"
    - name: add dave2001 to the pods
      ansible.builtin.include_role:
        name: user_setup
      vars:
        orcman: "dave2001"
        add_key: true
    - name: do_sudo
      ansible.builtin.include_role:
        name: do_sudo 
      vars:
        orcman: "dave2001"
