---
# tasks file for fix_repos
- name: fix centos6
  vars:
    repo_path: /etc/yum.repos.d/CentOS-Base.repo
  ansible.builtin.import_tasks:
    file: repo_fixer.yml
  when: iscentos6 is defined

- name: fix debian8
  vars:
    repo_path: /etc/apt/sources.list
  ansible.builtin.import_tasks:
    file: repo_fixer.yml
  when: isdebian8 is defined