---
- name: disable existing repo by commenting out lines
  ansible.builtin.replace:
    path: "{{ repo_path }}"
    backup: true
    regexp: '^(!#.+)$'  # match only if not commented out
    replace: '# \1'

- name: centos6 fixed repos
  ansible.builtin.blockinfile:
    path: "{{ repo_path }}"
    backup: true
    create: true
    owner: root
    group: root
    mode: 0644
    state: present
    marker: "# {mark} fixed repository {{ distribution_version }}"
    block: |
      [base]
      name=CentOS-"{{ distribution_version }}" - Base
      baseurl=https://linuxsoft.cern.ch/centos-vault/"{{ distribution_version }}"/os/x86_64/
      gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
      enabled=1
      metadata_expire=never

      #released updates
      [updates]
      name=CentOS-"{{ distribution_version }}" - Updates
      baseurl=https://linuxsoft.cern.ch/centos-vault/"{{ distribution_version }}"/updates/x86_64/
      gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
      enabled=1
      metadata_expire=never

      # additional packages that may be useful
      [extras]
      name=CentOS-"{{ distribution_version }}" - Extras
      baseurl=https://linuxsoft.cern.ch/centos-vault/"{{ distribution_version }}"/extras/x86_64/
      gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
      enabled=1
      metadata_expire=never

      # additional packages that extend functionality of existing packages
      [centosplus]
      name=CentOS-"{{ distribution_version }}" - CentOSPlus
      baseurl=https://linuxsoft.cern.ch/centos-vault/"{{ distribution_version }}"/centosplus/x86_64/
      gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
      enabled=0
      metadata_expire=never

      #contrib - packages by Centos Users
      [contrib]
      name=CentOS-"{{ distribution_version }}" - Contrib
      baseurl=https://linuxsoft.cern.ch/centos-vault/"{{ distribution_version }}"/contrib/x86_64/
      gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
      enabled=0
      metadata_expire=never
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version | int == 6

- name:  debian8 fixed repos
  ansible.builtin.blockinfile:
    path: "{{ repo_path }}"
    backup: true
    create: true
    owner: root
    group: root
    mode: 0644
    state: present
    marker: "# {mark} fixed repository {{ distribution_version }}"
    block: |
      deb http://deb.debian.org/debian/ jessie main
      deb http://security.debian.org/ jessie/updates main
  when: ansible_distribution == "Debian" and ansible_distribution_major_version | int == 8

- name:  debian8 fixed security certificates
  ansible.builtin.lineinfile:
    path: "/etc/apt/apt.conf"
    create: true
    owner: root
    group: root
    mode: '0440'
    line: "Acquire::Check-Valid-Until false;"
    state: present
  when: ansible_distribution == "Debian" and ansible_distribution_major_version | int == 8
