---
- name: create the new file
  ansible.builtin.file:
    path: "/etc/sudoers.d/{{ orcman }}"
    owner: root
    group: root
    mode: 0600
    state: touch
- name: Configure "{{ orcman }}" sudoers
  lineinfile:
    path: "/etc/sudoers.d/{{ orcman }}"
    regex: "^(#)?{{item.key}}"
    line: "{{item.key}} {{item.value}}"
    state: present
  loop:
    - { key: "Defaults", value: " secure_path = /bin:/sbin:/usr/bin:/usr/sbin" }
    - { key: "{{ orcman }}", value: " ALL=(ALL)  ALL" }
