---
- include_vars: "/depot/vault/{{ orcman }}.yml"
- name: adjust /etc/sudoers file
  ansible.builtin.import_tasks:
    file: adjust.yml
- name: configure sudoers
  ansible.builtin.import_tasks:
    file: configure.yml
